spring:
  application:
    name: reactive-messenger
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}
  kafka:
    bootstrapServers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    clientId: ${spring.application.name}
    producer:
      properties:
        transactional.id: tx
  r2dbc:
    username: ${SPRING_DATASOURCE_USERNAME:messenger_svc}
    password: ${SPRING_DATASOURCE_PASSWORD:messenger_svc}
    url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/messenger}
  liquibase:
    url: ${SPRING_LIQUIBASE_URL:jdbc:postgresql://localhost:5432/messenger}
    user: ${SPRING_LIQUIBASE_USER:messenger_svc}
    password: ${SPRING_LIQUIBASE_PASSWORD:messenger_svc}

server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful

logging:
  level:
    org.apache.kafka: DEBUG
    org.zalando.logbook: TRACE
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

app:
  kafka:
    messenger-topic: ${APP_KAFKA_MESSENGER_TOPIC:reactive_messenger}
    non-transactional-clientId: non-transactional-${spring.application.name}
